import {chromium} from 'file:///C:/Users/User/AppData/Local/npm-cache/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const out=fileURLToPath(new URL('.',import.meta.url)),css=await fs.readFile(out+'../../site/app/mercury-white.css','utf8'),prior=JSON.parse(await fs.readFile(out+'ui-progress.json','utf8'));
assert.equal(prior.length,21);assert.ok(prior.every(x=>x.pass));
await fs.copyFile(out+'ui-progress.json',out+'ui-first-21-preserved.json');
const browser=await chromium.launch({headless:true}),checks=prior.map(x=>({...x,reused:true})),errors=[],failures=[],mutations=[];
const apply=async p=>p.evaluate(css=>{const s=document.createElement('style');s.textContent=css;document.head.appendChild(s)},css);
const open=async options=>{const c=await browser.newContext({viewport:{width:1920,height:994},...options}),p=await c.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>failures.push({url:r.url(),reason:r.failure()?.errorText,context:options?.javaScriptEnabled===false?'no-js':'normal'}));p.on('request',r=>{if(r.method()!=='GET')mutations.push({url:r.url(),method:r.method()})});return {c,p}};
const check=async(name,fn)=>{try{checks.push({name,pass:true,evidence:await fn()})}catch(e){checks.push({name,pass:false,error:e.stack})}};
try {
 await check('no-JavaScript base document renders solid controls with QA-injected stylesheet',async()=>{const {c,p}=await open({javaScriptEnabled:false});try{await p.goto('http://127.0.0.1:5418/',{waitUntil:'networkidle'});await apply(p);const styles=await p.evaluate(()=>{const s=getComputedStyle(document.querySelector('.mc-market-open')),b=getComputedStyle(document.querySelector('.mc-quick-action.primary'));return {chip:s.backgroundColor,gradient:s.backgroundImage,service:b.backgroundColor,serviceGradient:b.backgroundImage}});assert.deepEqual(styles,{chip:'rgb(255, 223, 175)',gradient:'none',service:'rgb(255, 250, 240)',serviceGradient:'none'});await p.screenshot({path:out+'polish-no-js.png'});return styles}finally{await c.close()}});
 await check('stale editor palette and presets are ignored and untouched',async()=>{const {c,p}=await open();try{const stale='{"version":3,"palette":{"background":"#000000"}}',presets='private QA sentinel';await c.addInitScript(({stale,presets})=>{localStorage.setItem('mercury-skin-lab:palette:v1',stale);localStorage.setItem('mercury-skin-lab:presets:v1',presets)},{stale,presets});await p.goto('http://127.0.0.1:5418/',{waitUntil:'networkidle'});await apply(p);assert.equal(await p.locator('.mc-shell').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 250, 240)');assert.equal(await p.evaluate(()=>localStorage.getItem('mercury-skin-lab:palette:v1')),stale);assert.equal(await p.evaluate(()=>localStorage.getItem('mercury-skin-lab:presets:v1')),presets)}finally{await c.close()}});
 await check('runtime local request failures and transaction requests absent; external fonts recorded',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(failures.filter(r=>new URL(r.url).hostname==='127.0.0.1'&&r.context==='normal'),[]);assert.deepEqual(mutations,[]);const nojs=failures.filter(r=>new URL(r.url).hostname==='127.0.0.1'&&r.context==='no-js');assert.ok(nojs.every(r=>r.reason==='csp'));return {errors:0,localFailures:0,transactions:0,intentionalNoJsBlocks:nojs,blockedFonts:[...new Set(failures.filter(r=>r.reason==='net::ERR_NETWORK_ACCESS_DENIED').map(r=>r.url))]}});
}finally{await browser.close();const result={validationMode:'CSS injected into isolated browser contexts on unchanged f9 server; not a deployed or server-refreshed build',pass:checks.filter(c=>c.pass).length,fail:checks.filter(c=>!c.pass).length,reused:21,newChecks:3,checks,errors,requestFailures:failures,mutations,harnessCorrection:'addStyleTag awaited an event in JavaScript-disabled context; synchronous DOM style append used for that check. Already passed identical-input checks reused.'};await fs.writeFile(out+'ui-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({pass:result.pass,fail:result.fail,failures:checks.filter(c=>!c.pass)}));if(result.fail)process.exitCode=1}
