const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
const site=path.resolve(__dirname,'../../../site');
const baseline=JSON.parse(fs.readFileSync(path.join(__dirname,'audit-ready.json')));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const changed=baseline.files.filter(f=>sha(fs.readFileSync(path.join(site,f.path)))!==f.sha256).map(f=>f.path);
assert.deepEqual(changed,['app/globals.css','app/logo-presentation.json']);
const originalHash=p=>baseline.files.find(f=>f.path===p).sha256;
const css=fs.readFileSync(path.join(site,'app/globals.css'),'utf8');
const focus='.btn:focus-visible,.odd:focus-visible {outline:2px solid var(--ivory);outline-offset:2px;box-shadow:0 0 0 2px #171717;}';
assert(css.includes(focus));
assert.equal(sha(css.replace(focus,focus.replace('#171717;','#171717!important;'))),originalHash('app/globals.css'));
const logoPath='app/logo-presentation.json',logoText=fs.readFileSync(path.join(site,logoPath),'utf8');
const asset='/sports/r7/teams/nfl/new-york-jets.png',logos=JSON.parse(logoText);
assert.equal(logos[asset].backing,true);
const at=logoText.indexOf('"'+asset+'"'),end=logoText.indexOf('}',at);
const reverted=logoText.slice(0,at)+logoText.slice(at,end).replace('"backing": true','"backing": false')+logoText.slice(end);
assert.equal(sha(reverted),originalHash(logoPath));
const geometry=JSON.parse(fs.readFileSync(path.join(__dirname,'logo-geometry.json')));
geometry.find(x=>x.url===asset).backing=true;
fs.writeFileSync(path.join(__dirname,'logo-geometry-fixed.json'),JSON.stringify(geometry,null,2)+'\n');
const report={checkedAt:new Date().toISOString(),baselineSourceId:baseline.sourceId,changedSourceFiles:changed,unchangedSourceFiles:baseline.files.length-changed.length,exactDelta:['R7-F01: New York Jets backing false -> true only','R7-F02: remove !important from focus-visible box-shadow only; outline and active rules unchanged'],logos:{count:Object.keys(logos).length,backed:Object.values(logos).filter(x=>x.backing).length,withoutBacking:Object.values(logos).filter(x=>!x.backing).length,jetsAssetSha256:sha(fs.readFileSync(path.join(site,'public',asset))),allSourceAssetsUnchanged:true},status:'pass'};
fs.writeFileSync(path.join(__dirname,'fixes-static.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report));
