import {chromium} from 'file:///C:/Users/User/AppData/Local/npm-cache/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const out=fileURLToPath(new URL('.',import.meta.url)),mode=process.argv[2]||'after',b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:1920,height:994}}),p=await c.newPage();
const errors=[],failures=[],mutations=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>failures.push({url:r.url(),reason:r.failure()?.errorText}));p.on('request',r=>{if(r.method()!=='GET')mutations.push({url:r.url(),method:r.method()})});
const props=l=>l.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {color:s.color,background:s.backgroundColor,gradient:s.backgroundImage,border:s.borderColor,shadow:s.boxShadow,outline:s.outline,filter:s.filter,font:s.fontFamily,size:s.fontSize,width:r.width,height:r.height}});
const park=async()=>{await p.mouse.move(1919,993);await p.waitForTimeout(200);await p.evaluate(()=>document.activeElement?.blur())};
async function states(l,interactive=true){await park();const normal=await props(l);if(!interactive)return {normal};await l.hover();await p.waitForTimeout(200);const hover=await props(l);await park();await l.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');assert.ok(await l.evaluate(e=>e.matches(':focus-visible')));const focus=await props(l);return {normal,hover,focus}}
const evidence={mode,source:'Actual production server on 5418; no CSS injection',nonselected:{},selected:{},checks:[]};
try{
 const response=await p.goto('http://127.0.0.1:5418/',{waitUntil:'networkidle'});assert.equal(response.status(),200);assert.equal(await p.title(),'MERCURY · 화이트');await park();await p.screenshot({path:out+mode+'-first-entry.png'});evidence.cardGeometry=await p.locator('.mc-card').evaluateAll(es=>es.map(e=>({id:e.getAttribute('data-match-id'),rect:e.getBoundingClientRect().toJSON()})));
 for(const [name,selector,interactive] of [['primary','.mc-quick-action.primary',true],['secondary','.mc-quick-action.secondary',true],['userAction','.mc-user-actions button',true],['amount','.mc-amount-quick button:first-child',true],['max','.mc-amount-quick button:last-child',true],['level','.mc-user-head .mc-badge',false],['marketChip','.mc-market-open',true],['count','.mc-sport-tab[aria-pressed="true"] .mc-sport-count',false],['normalSport','.mc-sport-tab[data-sport="soccer"]',true],['normalMarket','.mc-market-tabs button:nth-child(2)',true],['normalOdds','.mc-list-pane .mc-odd:not(:disabled)',true],['disabled','.mc-bet-submit',false]])evidence.nonselected[name]=await states(p.locator(selector).first(),interactive);
 await park();evidence.images=await p.locator('.mc-shell img').evaluateAll(es=>es.map(e=>({src:e.getAttribute('src'),naturalWidth:e.naturalWidth,width:e.clientWidth,height:e.clientHeight,filter:getComputedStyle(e).filter})));
 if(mode==='after'){
  const prior=JSON.parse(await fs.readFile(out+'before-state-reference.json','utf8')),reference=JSON.parse(await fs.readFile(out+'f9-selected-reference.json','utf8'));
  assert.deepEqual(evidence.nonselected,prior.nonselected);evidence.checks.push({name:'12 nonselected families across normal hover focus and disabled exactly preserve 697',pass:true});assert.deepEqual(evidence.images,prior.images);evidence.checks.push({name:'164 image paths sizes and filters unchanged from 697',pass:true});
  const odd=p.locator('.mc-list-pane .mc-odd:not(:disabled)').first();await odd.click();await park();
  for(const [name,selector]of [['sport','.mc-sport-tab[aria-pressed="true"]'],['market','.mc-market-tabs button[aria-pressed="true"]'],['odds','.mc-list-pane .mc-odd[aria-pressed="true"]']]){evidence.selected[name]=await states(p.locator(selector).first());assert.deepEqual(evidence.selected[name],reference.groups[name],name);evidence.checks.push({name:name+' selected normal hover focus exactly reproduce f9 equivalent approved v6',pass:true})}
  await p.getByLabel('베팅 금액',{exact:true}).fill('5000');assert.equal(await p.locator('.mc-payout-value').innerText(),'7,800');assert.equal(await p.locator('.mc-bet-submit').isDisabled(),true);evidence.checks.push({name:'selected odds behavior and 5000 × 1.56 = 7800 unchanged; no transaction',pass:true});await park();await p.screenshot({path:out+'after-selected.png'});await p.locator('.mc-sportbar').screenshot({path:out+'after-sports.png'});await p.locator('.mc-list-pane .mc-card').first().screenshot({path:out+'after-odds.png'});await p.locator('.mc-quick').screenshot({path:out+'after-quick.png'});
 }
 assert.deepEqual(errors,[]);assert.deepEqual(mutations,[]);assert.deepEqual(failures.filter(e=>e.url.startsWith('http://127.0.0.1')),[]);evidence.checks.push({name:'runtime local assets and transaction requests healthy',pass:true});evidence.errors=errors;evidence.requestFailures=failures;evidence.mutations=mutations;evidence.pass=evidence.checks.length;evidence.fail=0;
 await fs.writeFile(out+(mode==='before'?'before-state-reference.json':'selected-restoration-results.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify({mode,pass:evidence.pass,fail:0,nonselectedFamilies:Object.keys(evidence.nonselected).length,images:evidence.images.length}));
}catch(e){evidence.error=e.stack;evidence.fail=1;await fs.writeFile(out+mode+'-failure.json',JSON.stringify(evidence,null,2));console.error(e.stack);process.exitCode=1}finally{await c.close();await b.close()}
