const fs=require('node:fs'),crypto=require('node:crypto');
const q='../qa/r8/right-banner-20260918',read=f=>JSON.parse(fs.readFileSync(q+'/'+f,'utf8').replace(/^\uFEFF/,''));
const tech=read('technical-checks.json'),release=read('deployment.json'),http=read('anonymous-public.json'),browser=read('public-browser.json'),local=read('local-checks.json');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const sourceHash=sha(tech.source),copyHash=sha(tech.copy),leftHash=sha('public/banners/r8/mercury-slots-woman.png');
if(sourceHash!==copyHash||sourceHash!==http.image.sha256)throw Error('Image hashes differ');
if(leftHash!=='82957c0e5197bd2d3a2983bd260c8284632507f821251c8b76918dd0b2e600a6')throw Error('Left image changed');
const result={status:'complete',completedAt:new Date().toISOString(),url:release.deployment.url,changedFiles:['site/app/page.tsx','site/public/banners/r8/mercury-event-woman.png'],change:'Right PhotoBanner image path only; new original PNG copied byte-for-byte.',source:tech.source,asset:{path:tech.copy,sourceSha256:sourceHash,copySha256:copyHash,publicSha256:http.image.sha256,bytes:tech.image.bytes,dimensions:[1672,941]},crop:{objectFit:'cover',objectPosition:'30% 50%',changed:false},public:{version:release.version.version_number,versionId:release.version.id,deploymentId:release.deployment.id,commit:release.version.source.commit_sha,status:release.deployment.status,publishedAt:release.deployment.updated_at,access:'public'},verification:{build:'PASS',diffCheck:'PASS',package:'PASS',localBanner:'PASS',localEventCTA:'PASS',anonymousPublicPage:'HTTP 200',anonymousPublicImage:'HTTP 200; original SHA-256 match',publicBannerVisual:'PASS',publicCaptureDimensions:[1920,940]},capture:{path:'qa/r8/right-banner-20260918/'+browser.capture,format:'JPEG',width:1920,height:940,sha256:sha(q+'/'+browser.capture)},preserved:{leftImageSha256:leftHash,copyCTAFrameCSS:true,otherSource:true,coordinatorDocs:'Not edited',preExistingUntracked:'tsconfig.tsbuildinfo'},unverified:['Unchanged whole-site regression and 77-fixture audit intentionally not repeated.','Event CTA interaction checked on local production build; public page verified visually and by anonymous asset/source readback.'],remainingRisks:[],excludedCaptures:[local.excludedCapture,browser.excludedCapture],toolingNote:tech.toolingNote};
fs.writeFileSync(q+'/completion.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
