import { run } from './ae-client.mjs';
const M='TITAN_MASTER_20S',D='DEVICE_iPad10_3D',S='SCREEN_iPad10_CAT_VIDEO_CONTAIN';
const ivory=[0.961,0.953,0.933], ink=[0.137,0.153,0.173], charcoal=[0.137,0.149,0.161], orange=[1,0.47,0.04];
const ops=[];
const op=(operation,args)=>ops.push({operation,args});
const props=(comp,layer,values)=>op('layer.set_props',{comp,layer,props:values});
const tr=(comp,layer,values)=>op('transform.set',{comp,layer,...values});
const text=(name,copy,font,size,color,pos,outline=false)=>{
 op('layer.create_text',{comp:M,name,text:copy});
 op('text.set_style',{comp:M,layer:name,font,fontSize:size,fillColor:color,strokeColor:color,applyFill:!outline,applyStroke:outline,strokeWidth:outline?2:0,tracking:-20,justification:'left',autoKernType:'metric',fauxBold:false,fauxItalic:false});
 tr(M,name,{position:pos,anchorPoint:[0,0]});
};
op('layer.create_solid',{comp:S,name:'Contain_Dark_Padding',color:[0.015,0.017,0.02]});
op('layer.create_footage',{comp:S,sourceItemId:38,name:'CAT_Original_60fps_100percent'});
props(S,'CAT_Original_60fps_100percent',{startTime:1.8,inPoint:1.8,outPoint:20,audioEnabled:false});
tr(S,'CAT_Original_60fps_100percent',{position:[1180,820],scale:[122.9166666667,122.9166666667]});
op('layer.create_footage',{comp:D,sourceItemId:25,name:'SCREEN_MATERIAL_SOURCE'});
props(D,'SCREEN_MATERIAL_SOURCE',{enabled:false,audioEnabled:false});
op('layer.create_footage',{comp:D,sourceItemId:37,name:'iPad10_MODEL'});
tr(D,'iPad10_MODEL',{position:[1200,512,0],scale:[100,100,100]});
op('layer.create_light',{comp:D,name:'Environment_Soft_Studio',lightType:'environment'});
op('layer.create_camera',{comp:D,name:'Camera_Product'});
op('layer.create_solid',{comp:M,name:'BG_Ivory',color:ivory});
op('layer.create_solid',{comp:M,name:'BG_Charcoal_Reveal',color:charcoal});
props(M,'BG_Charcoal_Reveal',{inPoint:31/30,outPoint:125/30});
text('S01_TITAN_Outline','TITAN','Pretendard-Bold',850,ink,[42,635],true);
props(M,'S01_TITAN_Outline',{outPoint:45/30});
text('S02_BUILT_Outline','BUILT','Pretendard-Bold',910,ivory,[-85,800],true);
props(M,'S02_BUILT_Outline',{inPoint:68/30,outPoint:118/30});
op('layer.create_footage',{comp:M,sourceItemId:13,name:'S03_iPad_REAL_3D'});
props(M,'S03_iPad_REAL_3D',{inPoint:114/30,outPoint:5.7,audioEnabled:false});
text('S01_Meet','Meet','Pretendard-Regular',176,ink,[680,685]);
text('S01_TITAN','TITAN','Pretendard-Bold',238,ink,[1100,685]);
props(M,'S01_Meet',{outPoint:45/30}); props(M,'S01_TITAN',{outPoint:45/30});
text('S02_Core_systems','Core systems','Pretendard-Regular',106,ivory,[700,430]);
text('S02_Built','Built','Pretendard-Bold',182,orange,[700,591]);
text('S02_in_house','in-house','Pretendard-SemiBold',158,ivory,[1138,591]);
props(M,'S02_Core_systems',{inPoint:39/30,outPoint:118/30}); props(M,'S02_Built',{inPoint:66/30,outPoint:118/30});props(M,'S02_in_house',{inPoint:93/30,outPoint:118/30});
text('S03_CAT_Fill','CAT VILLAGE','Pretendard-Bold',370,ink,[108,539]);
text('S03_CAT_Outline','CAT VILLAGE','Pretendard-Bold',370,ink,[108,539],true);
text('S03_Casino_Fill','Casino Slot','Pretendard-SemiBold',194,ink,[690,690]);
text('S03_Casino_Outline','Casino Slot','Pretendard-SemiBold',194,ivory,[690,690],true);
for(const n of ['S03_CAT_Fill','S03_CAT_Outline','S03_Casino_Fill','S03_Casino_Outline']) props(M,n,{inPoint:114/30,outPoint:5.7});
for(const [i,id] of [[1,39],[2,40],[3,41]]) {
 const n=`REFERENCE_0${i}_GUIDE_DISABLED`;op('layer.create_footage',{comp:M,sourceItemId:id,name:n});tr(M,n,{scale:[125,125],position:[1200,512]});op('layer.set_guide',{comp:M,layer:n,guide:true});props(M,n,{enabled:false,locked:true});
}
op('timeline.set_time',{comp:M,time:0});
op('layer.apply_preset',{comp:M,layer:'S01_Meet',path:'C:/Program Files/Adobe/Adobe After Effects (Beta)/Support Files/Presets/Text/3D Text/3D Basic Rotate X Cascade In.ffx'});
op('timeline.set_time',{comp:M,time:114/30});
op('layer.apply_preset',{comp:M,layer:'S03_CAT_Fill',path:'C:/Program Files/Adobe/Adobe After Effects (Beta)/Support Files/Presets/Text/Animate In/Slide Up By Word.ffx'});
await run({write:true,compact:true,calls:[{name:'ae_do',args:{operation:'batch.run',args:{ops,stopOnError:true},timeoutMs:60000}},{name:'ae_layer_info',args:{compNameOrId:M,layerIndex:[14,7]}},{name:'ae_comp_info',args:{compNameOrId:D}}]});
