import {chromium} from 'file:///C:/Users/User/AppData/Local/npm-cache/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const out=fileURLToPath(new URL('.',import.meta.url)),before=JSON.parse(await fs.readFile(out+'before-state-reference.json','utf8')),reference=JSON.parse(await fs.readFile(out+'../selected-restore-20261007-083206/f9-selected-reference.json','utf8'));
const b=await chromium.launch({headless:true}),c=await b.newContext({viewport:{width:1920,height:994}}),p=await c.newPage(),checks=[],errors=[],failures=[],mutations=[];
p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>failures.push({url:r.url(),reason:r.failure()?.errorText}));p.on('request',r=>{if(r.method()!=='GET')mutations.push({url:r.url(),method:r.method()})});
const props=l=>l.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {color:s.color,background:s.backgroundColor,gradient:s.backgroundImage,border:s.borderColor,shadow:s.boxShadow,outline:s.outline,filter:s.filter,font:s.fontFamily,size:s.fontSize,width:r.width,height:r.height}});
const park=async()=>{await p.mouse.move(1919,993);await p.waitForTimeout(200);await p.evaluate(()=>document.activeElement?.blur())};
const states=async(l,interactive=true)=>{await park();const normal=await props(l);if(!interactive)return {normal};await l.hover();await p.waitForTimeout(200);const hover=await props(l);await park();await l.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');assert.ok(await l.evaluate(e=>e.matches(':focus-visible')));return {normal,hover,focus:await props(l)}};
const check=async(name,fn)=>{try{checks.push({name,pass:true,evidence:await fn()})}catch(e){checks.push({name,pass:false,error:e.stack})}};
const lum=a=>a.map(x=>x/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((v,c,i)=>v+c*[.2126,.7152,.0722][i],0),rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number),contrast=(a,b)=>{const [lo,hi]=[lum(rgb(a)),lum(rgb(b))].sort((a,b)=>a-b);return (hi+.05)/(lo+.05)};
try{
 const r=await p.goto('http://127.0.0.1:5418/',{waitUntil:'networkidle'});assert.equal(r.status(),200);assert.equal(await p.title(),'MERCURY · 화이트');await park();await p.screenshot({path:out+'first-entry.png'});
 await check('all match-card geometry unchanged; outline does not cause layout shift',async()=>{const actual=await p.locator('.mc-card').evaluateAll(es=>es.map(e=>({id:e.getAttribute('data-match-id'),rect:e.getBoundingClientRect().toJSON()})));assert.deepEqual(actual,before.cardGeometry);return {cards:actual.length}});
 await check('exact header menu gradient reused on three services in normal hover focus',async()=>{const header=(await props(p.locator('.mc-menu-panel'))).gradient,buttons=p.locator('.mc-quick-action.primary');assert.equal(await buttons.count(),3);assert.deepEqual(await buttons.allTextContents(),['충전','환전','고객센터']);const stops=[...header.matchAll(/rgb\([^)]+\)/g)].map(m=>m[0]),evidence=[];for(let i=0;i<3;i++){const button=buttons.nth(i),s=await states(button);for(const v of Object.values(s)){assert.equal(v.gradient,header);assert.equal(v.filter,'none');const minimum=Math.min(...stops.map(bg=>contrast(v.color,bg)));assert.ok(minimum>=4.5);v.minTextContrast=minimum;}const mask=await button.locator('.mc-ui-icon-mask').evaluate(e=>getComputedStyle(e).backgroundColor);assert.equal(mask,s.normal.color);evidence.push({text:await button.innerText(),states:s,mask})}await park();await p.locator('.mc-quick').screenshot({path:out+'services.png'});return {header,evidence}});
 await check('other eleven normal/hover/focus/disabled families keep exact prior polish',async()=>{const data={};for(const [name,selector,interactive]of [['secondary','.mc-quick-action.secondary',true],['userAction','.mc-user-actions button',true],['amount','.mc-amount-quick button:first-child',true],['max','.mc-amount-quick button:last-child',true],['level','.mc-user-head .mc-badge',false],['marketChip','.mc-market-open',true],['count','.mc-sport-tab[aria-pressed="true"] .mc-sport-count',false],['normalSport','.mc-sport-tab[data-sport="soccer"]',true],['normalMarket','.mc-market-tabs button:nth-child(2)',true],['normalOdds','.mc-list-pane .mc-odd:not(:disabled)',true],['disabled','.mc-bet-submit',false]]){data[name]=await states(p.locator(selector).first(),interactive);assert.deepEqual(data[name],before.nonselected[name],name)}return {families:Object.keys(data).length}});
 await check('selected whole card outline survives hover and nested keyboard focus',async()=>{const card=p.locator('.mc-card').first(),baseline=await props(card);assert.equal(await card.getAttribute('data-inspected'),'true');assert.equal(baseline.border,'rgb(183, 96, 22)');assert.match(baseline.shadow,/1px inset/);assert.ok(contrast(baseline.border,baseline.background)>=3);await card.hover({position:{x:10,y:10}});await p.waitForTimeout(200);const hover=await props(card);assert.deepEqual(hover,baseline);const child=card.locator('.mc-card-inspect');await child.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');assert.ok(await child.evaluate(e=>e.matches(':focus-visible')));const focus=await props(card);assert.deepEqual(focus,baseline);await park();await card.screenshot({path:out+'inspected-card.png'});return {normal:baseline,hover,focus,borderContrast:contrast(baseline.border,baseline.background)}});
 await check('chosen betting card remains outlined when another match is inspected',async()=>{const first=p.locator('.mc-card').first(),second=p.locator('.mc-card').nth(1);await first.locator('.mc-odd:not(:disabled)').first().click();await second.locator('.mc-market-open').click();await park();assert.equal(await first.getAttribute('data-inspected'),'false');assert.equal(await second.getAttribute('data-inspected'),'true');assert.equal((await props(first)).border,'rgb(183, 96, 22)');assert.equal((await props(second)).border,'rgb(183, 96, 22)');assert.equal(await p.locator('.mc-slip-selection').count(),1);await first.screenshot({path:out+'chosen-card.png'});await first.locator('.mc-odd[aria-pressed="true"]').click();assert.equal((await props(first)).border,'rgb(201, 199, 187)');await first.locator('.mc-market-open').click();return {chosenOutlinePersists:true,deselectedUninspectedOutlineClears:true}});
 await check('approved selected sport odds and market styling remains exact',async()=>{await p.locator('.mc-list-pane .mc-odd:not(:disabled)').first().click();const evidence={};for(const [name,selector]of [['sport','.mc-sport-tab[aria-pressed="true"]'],['market','.mc-market-tabs button[aria-pressed="true"]'],['odds','.mc-list-pane .mc-odd[aria-pressed="true"]']]){evidence[name]=await states(p.locator(selector).first());assert.deepEqual(evidence[name],reference.groups[name],name)}await p.getByLabel('베팅 금액',{exact:true}).fill('5000');assert.equal(await p.locator('.mc-payout-value').innerText(),'7,800');assert.equal(await p.locator('.mc-bet-submit').isDisabled(),true);await park();await p.getByRole('complementary',{name:'계정과 베팅슬립'}).evaluate(e=>e.scrollTop=0);await p.screenshot({path:out+'selected-full.png'});return {evidence,payout:7800,transactions:0}});
 await check('three services still open correct popups without execution',async()=>{const headings=[];for(const [i,title]of [[0,'충전'],[1,'환전 안내'],[2,'고객센터']]){await p.locator('.mc-quick-action.primary').nth(i).click();assert.equal(await p.getByRole('dialog').getByRole('heading').innerText(),title);headings.push(title);await p.getByRole('button',{name:'닫기',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'})}assert.equal(await p.locator('.mc-balance-value').innerText(),'1,000,000 원');return headings});
 await check('all images and runtime preserved; no transaction request',async()=>{const images=await p.locator('.mc-shell img').evaluateAll(es=>es.map(e=>({src:e.getAttribute('src'),naturalWidth:e.naturalWidth,width:e.clientWidth,height:e.clientHeight,filter:getComputedStyle(e).filter})));assert.deepEqual(images,before.images);assert.deepEqual(errors,[]);assert.deepEqual(mutations,[]);assert.deepEqual(failures.filter(r=>r.url.startsWith('http://127.0.0.1')),[]);return {images:images.length,errors:0,localFailures:0,transactions:0,blockedFonts:[...new Set(failures.filter(r=>r.reason==='net::ERR_NETWORK_ACCESS_DENIED').map(r=>r.url))]}});
}finally{await c.close();await b.close();const result={pass:checks.filter(c=>c.pass).length,fail:checks.filter(c=>!c.pass).length,mode:'Actual new production build on 5418; no stylesheet injection',checks,errors,failures,mutations};await fs.writeFile(out+'qa-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({pass:result.pass,fail:result.fail,failures:checks.filter(c=>!c.pass)}));if(result.fail)process.exitCode=1}
