import {chromium} from 'file:///C:/Users/User/AppData/Local/npm-cache/_npx/705bc6b22212b352/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const out=fileURLToPath(new URL('.',import.meta.url)),input=JSON.parse(await fs.readFile(out+'../input/mercury-palette_98.json','utf8')),reference=JSON.parse(await fs.readFile(out+'editor-approved-reference.json','utf8'));
const browser=await chromium.launch({headless:true}),checks=[],errors=[],requestFailures=[],consoleErrors=[],mutations=[];
async function open(options={}){const ctx=await browser.newContext({viewport:{width:1920,height:994},...options}),p=await ctx.newPage();p.setDefaultTimeout(9000);p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>requestFailures.push({url:r.url(),reason:r.failure()?.errorText}));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});p.on('request',r=>{if(r.method()!=='GET')mutations.push({method:r.method(),url:r.url()})});return {ctx,p}}
const check=async(name,fn)=>{try{checks.push({name,pass:true,evidence:await fn()})}catch(e){checks.push({name,pass:false,error:e.stack})}await fs.writeFile(out+'ui-progress.json',JSON.stringify(checks,null,2))};
const settle=async p=>p.waitForTimeout(450);
const park=async p=>{await p.mouse.move(1919,993);await settle(p)};
const computed=el=>el.evaluate(e=>{const s=getComputedStyle(e);return {color:s.color,bg:s.backgroundImage,backgroundColor:s.backgroundColor,border:s.borderColor,filter:s.filter,font:s.fontFamily,fontSize:s.fontSize,rect:e.getBoundingClientRect().toJSON()}});
const all=p=>p.locator('.mc-sport-tab[data-sport="all"]');
const slip=p=>p.locator('.mc-slip-selection');
async function reset(p){await p.reload({waitUntil:'networkidle'});await p.waitForSelector('.mc-shell');await park(p)}
async function close(p){await p.getByRole('button',{name:'닫기',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});}
let ctx,p;
try{
 ({ctx,p}=await open());const response=await p.goto('http://127.0.0.1:5418/',{waitUntil:'networkidle'});assert.equal(response.status(),200);await park(p);
 await check('fresh first entry uses all approved colors without saved palette',async()=>{const vars=await p.evaluate(keys=>Object.fromEntries(keys.map(k=>[k,getComputedStyle(document.documentElement).getPropertyValue('--skin-'+k).trim()])),Object.keys(input.palette));assert.deepEqual(vars,input.palette);assert.equal(await p.evaluate(()=>localStorage.getItem('mercury-skin-lab:palette:v1')),null);assert.equal(await p.evaluate(()=>localStorage.getItem('mercury-skin-lab:presets:v1')),null);return vars});
 await check('site only; editor picker QA lane absent',async()=>{assert.equal(await p.locator('#skin-editor,.skin-launcher,.skin-picker-layer,.skin-workspace,[data-skin-picker-ui]').count(),0);assert.equal(await p.title(),'MERCURY · 화이트');const sizes=await p.evaluate(()=>({body:getComputedStyle(document.body).minWidth,scroll:document.documentElement.scrollWidth,width:document.querySelector('.mercury-site').getBoundingClientRect().width}));assert.equal(sizes.body,'1920px');assert.equal(sizes.scroll,1920);assert.equal(sizes.width,1920);return sizes});
 const selectors={shell:'.mc-shell',header:'.mc-header',body:'.mc-body',sportbar:'.mc-sportbar',league:'.mc-league-label',card:'.mc-card',level:'.mc-user-head .mc-badge',sports:'.mc-sports-summary .mc-badge',menu:'.mc-menu-badge',marketChip:'.mc-market-open',selectedCount:'.mc-sport-tab[aria-pressed="true"] .mc-sport-count',selectedSport:'.mc-sport-tab[aria-pressed="true"]',headerButton:'.mc-auth button',normalOdds:'.mc-odd:not(.is-selected)'};
 await check('approved editor render colors typography and geometry reproduced',async()=>{const evidence={};for(const [k,sel]of Object.entries(selectors)){const value=await computed(p.locator(sel).first());assert.deepEqual(value,reference.css[k],k);evidence[k]=value;}await p.locator('.mc-shell').screenshot({path:out+'white-first-entry.png'});return evidence});
 await check('all image paths dimensions filters preserved and local assets loaded',async()=>{const images=await p.locator('.mc-shell img').evaluateAll(es=>es.map(e=>({src:e.getAttribute('src'),naturalWidth:e.naturalWidth,width:e.clientWidth,height:e.clientHeight,filter:getComputedStyle(e).filter})));assert.deepEqual(images,reference.images);assert.ok(images.every(e=>e.naturalWidth>0));return {count:images.length}});
 await check('Guest balance full count and disabled inactive categories preserved',async()=>{assert.equal(await all(p).locator('.mc-sport-count').innerText(),'61');assert.equal(await p.locator('.mc-list-pane .mc-card').count(),61);assert.equal(await p.locator('.mc-bet-submit').isDisabled(),true);assert.equal(await p.locator('.mc-balance-value').innerText(),'1,000,000 원');assert.equal(await p.locator('.mc-menu-item:disabled').count(),8);return {matches:61,balance:'1,000,000',guestSubmitDisabled:true}});
 await check('chips orange gradient and header/league actual supplied colors',async()=>{const chip=await computed(p.locator('.mc-market-open').first());assert.equal(chip.bg,'linear-gradient(rgb(255, 219, 158) 0%, rgb(255, 190, 10) 100%)');assert.equal(chip.border,'rgb(255, 181, 97)');assert.equal(chip.color,'rgb(0, 0, 0)');assert.equal((await computed(p.locator('.mc-league-label').first())).color,'rgb(0, 0, 0)');assert.equal((await computed(p.locator('.mc-auth button').first())).backgroundColor,'rgb(99, 99, 99)');return chip});
 await check('sport filters counts selected fill and empty state operate',async()=>{await p.locator('.mc-sport-tab[data-sport="soccer"]').click();await settle(p);assert.equal(await p.locator('.mc-list-pane .mc-card').count(),32);assert.equal((await computed(p.locator('.mc-sport-tab[data-sport="soccer"]'))).backgroundColor,'rgb(255, 194, 111)');await p.locator('.mc-sport-tab[data-sport="volleyball"]').click();await p.locator('.mc-list-pane .mc-empty').waitFor();assert.equal(await p.locator('.mc-list-pane .mc-card').count(),0);await p.locator('.mc-list-pane .mc-small-action').click();assert.equal(await p.locator('.mc-list-pane .mc-card').count(),61)});
 await check('team search and clear restore full list',async()=>{const search=p.getByLabel('해외형 스포츠 검색',{exact:true});await search.fill('토론토');await settle(p);const count=await p.locator('.mc-list-pane .mc-card').count();assert.ok(count>0&&count<61);await p.getByRole('button',{name:'해외형 검색어 지우기',exact:true}).click();assert.equal(await p.locator('.mc-list-pane .mc-card').count(),61);return {filteredCount:count}});
 await check('league folding and reopening retain dimensions',async()=>{const fold=p.locator('.mc-league-head').first(),id=await fold.getAttribute('aria-controls'),body=p.locator('[id="'+id+'"]'),before=await body.boundingBox();await fold.click();assert.equal(await fold.getAttribute('aria-expanded'),'false');await settle(p);assert.ok((await body.boundingBox()).height<1);await fold.click();await settle(p);assert.equal(await fold.getAttribute('aria-expanded'),'true');assert.deepEqual(await body.boundingBox(),before)});
 await check('market chip opens correct match and detail filters work',async()=>{const card=p.locator('.mc-list-pane .mc-card').nth(1),id=await card.getAttribute('data-match-id');await card.locator('.mc-market-open').click();await p.waitForFunction(id=>document.querySelector('[data-detail-match]')?.getAttribute('data-detail-match')===id,id);await p.locator('.mc-market-tabs button').filter({hasText:'핸디캡'}).click();assert.equal(await p.locator('.mc-market-tabs button[aria-pressed="true"]').innerText(),'핸디캡');await p.locator('.mc-market-tabs button').filter({hasText:'전체'}).click();return {detailMatch:id}});
 await reset(p);
 await check('odds select replacement and deselect preserve slip ids',async()=>{const card=p.locator('.mc-list-pane .mc-card').first(),odd=card.locator('.mc-odd:not(:disabled)').first(),id=await odd.getAttribute('data-selection-id');await odd.click();assert.equal(await slip(p).count(),1);assert.equal(await slip(p).getAttribute('data-selection'),id);await odd.click();assert.equal(await slip(p).count(),0);await odd.click();const replacement=card.locator('.mc-odd:not(:disabled)').nth(1),other=await replacement.getAttribute('data-selection-id');await replacement.click();assert.equal(await slip(p).count(),1);assert.equal(await slip(p).getAttribute('data-selection'),other);return {id,replacement:other}});
 await reset(p);
 await check('warm selected odds and stake calculation use unchanged behavior',async()=>{const odd=p.locator('.mc-list-pane .mc-odd:not(:disabled)').first();await odd.click();await p.getByLabel('베팅 금액',{exact:true}).fill('5000');await settle(p);const s=await computed(odd);assert.equal(s.border,'rgb(255, 136, 0)');assert.equal(s.color,'rgb(0, 0, 0)');assert.match(s.bg,/linear-gradient/);assert.equal(await p.locator('[data-total-odds]').innerText(),'1.56 배');assert.equal(await p.locator('.mc-payout-value').innerText(),'7,800');assert.equal(await p.locator('.mc-bet-submit').isDisabled(),true);await p.locator('.mc-shell').screenshot({path:out+'white-selection-stake.png'});return {selected:s,totalOdds:'1.56',payout:7800,submitted:0}});
 await check('invalid amount and reset remain functional',async()=>{await p.getByLabel('베팅 금액',{exact:true}).fill('1');assert.equal(await p.getByLabel('베팅 금액',{exact:true}).getAttribute('aria-invalid'),'true');assert.equal(await p.locator('.mc-slip-hint').first().evaluate(e=>getComputedStyle(e).color),'rgb(255, 30, 0)');await p.locator('.mc-reset').click();assert.equal(await p.getByLabel('베팅 금액',{exact:true}).inputValue(),'');await p.locator('.mc-slip').getByRole('button',{name:'전체삭제',exact:true}).click();assert.equal(await slip(p).count(),0)});
 await check('keep-slip reload restores selection and stake only in isolated storage',async()=>{await p.locator('.mc-list-pane .mc-odd:not(:disabled)').first().click();await p.getByLabel('베팅 금액',{exact:true}).fill('5000');const id=await slip(p).getAttribute('data-selection');await p.locator('.mc-slip-toggle').click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('mercury-demo-r6-v1-slip')).keep===true);await reset(p);assert.equal(await slip(p).getAttribute('data-selection'),id);assert.equal(await p.getByLabel('베팅 금액',{exact:true}).inputValue(),'5,000');const session=JSON.parse(await p.evaluate(()=>localStorage.getItem('mercury-demo-r6-v1')));assert.equal(session.balance,1000000);assert.equal(session.history.length,0);await p.locator('.mc-slip-toggle').click();return {id,balance:session.balance,history:0}});
 await reset(p);
 await check('support event history and charge/withdraw popups open and close without execution',async()=>{const records=[];for(const [sel,title]of [['.mc-quick-action.primary:nth-child(3)','고객센터'],['.mc-quick-action.primary:first-child','충전'],['.mc-quick-action.primary:nth-child(2)','환전 안내'],['.mc-user-actions button:last-child','내 베팅내역'],['.mc-quick-action:not(.primary):first-of-type','이벤트']]){let button=p.locator(sel);if(title==='이벤트')button=p.locator('.mc-quick-action').filter({hasText:'이벤트'}).first();await button.click();await p.getByRole('dialog').waitFor();assert.equal(await p.getByRole('dialog').getByRole('heading').innerText(),title);records.push(title);if(title==='고객센터')await p.screenshot({path:out+'white-support-popup.png'});await close(p);}assert.equal(await p.locator('.mc-balance-value').innerText(),'1,000,000 원');return {popups:records,transactionExecutions:0}});
 await check('domestic and european navigation preserve slip and layout modes',async()=>{await p.locator('.mc-menu-item').filter({hasText:'국내형 스포츠'}).click();assert.equal(await p.locator('.mc-center').getAttribute('data-mode'),'domestic');assert.equal(await p.locator('[data-detail-match]').count(),0);await p.locator('.mc-menu-item').filter({hasText:'해외형 스포츠'}).click();assert.equal(await p.locator('.mc-center').getAttribute('data-mode'),'european');assert.equal(await p.locator('[data-detail-match]').count(),1)});
 await check('hover and keyboard focus retain authored selected/chip styling',async()=>{const chip=p.locator('.mc-market-open').first();await park(p);const normal=await computed(chip);await chip.hover();await settle(p);const hover=await computed(chip);for(const k of ['color','bg','backgroundColor','border','rect'])assert.deepEqual(hover[k],normal[k]);await park(p);await chip.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');assert.ok(await chip.evaluate(e=>e.matches(':focus-visible')));assert.match(await chip.evaluate(e=>getComputedStyle(e).outline),/2px/);return {normal,hover}});
 await check('independent pane scrolling preserves fixed header and right pane',async()=>{const list=p.locator('.mc-list-scroll'),right=p.getByRole('complementary',{name:'계정과 베팅슬립'}),before=await computed(p.locator('.mc-header'));const rightBefore=await right.evaluate(e=>e.scrollTop);await list.evaluate(e=>e.scrollTop=200);assert.ok(await list.evaluate(e=>e.scrollTop)>0);assert.equal(await right.evaluate(e=>e.scrollTop),rightBefore);assert.deepEqual(await computed(p.locator('.mc-header')),before);await list.evaluate(e=>e.scrollTop=0)});
 for(const width of [2560,1920,1366])await check('fixed canvas alignment and access at '+width,async()=>{await p.setViewportSize({width,height:994});await p.evaluate(()=>window.scrollTo(0,0));await settle(p);const s=await p.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,shell:document.querySelector('.mc-shell').getBoundingClientRect().toJSON(),body:getComputedStyle(document.body).minWidth}));assert.equal(s.shell.width,1920);assert.equal(s.shell.x,Math.max(0,(width-1920)/2));assert.equal(s.scroll,Math.max(width,1920));assert.equal(s.body,'1920px');if(width<1920){await p.evaluate(()=>window.scrollTo(1920,0));assert.equal(await p.evaluate(()=>window.scrollX),1920-width);const x=(await p.locator('.mc-user-head .mc-small-action').boundingBox()).x;assert.ok(x>=0&&x<width);await p.screenshot({path:out+'white-narrow-right.png'});}if(width===2560)await p.screenshot({path:out+'white-wide.png'});return s});
 await ctx.close();ctx=null;
 await check('no-JavaScript first paint still has approved white theme',async()=>{const other=await open({javaScriptEnabled:false});try{await other.p.goto('http://127.0.0.1:5418/',{waitUntil:'networkidle'});const shell=await computed(other.p.locator('.mc-shell'));assert.equal(shell.backgroundColor,'rgb(255, 250, 240)');assert.equal((await computed(other.p.locator('.mc-league-label').first())).color,'rgb(0, 0, 0)');assert.equal((await computed(other.p.locator('.mc-market-open').first())).bg,'linear-gradient(rgb(255, 219, 158) 0%, rgb(255, 190, 10) 100%)');await other.p.screenshot({path:out+'white-no-js.png'});return shell;}finally{await other.ctx.close()}});
 await check('stale editor palette and presets are ignored and untouched',async()=>{const other=await open();try{const stale='{"version":3,"palette":{"background":"#000000"}}',presets='private QA sentinel';await other.ctx.addInitScript(({stale,presets})=>{localStorage.setItem('mercury-skin-lab:palette:v1',stale);localStorage.setItem('mercury-skin-lab:presets:v1',presets)},{stale,presets});await other.p.goto('http://127.0.0.1:5418/',{waitUntil:'networkidle'});assert.equal((await computed(other.p.locator('.mc-shell'))).backgroundColor,'rgb(255, 250, 240)');assert.equal(await other.p.evaluate(()=>localStorage.getItem('mercury-skin-lab:palette:v1')),stale);assert.equal(await other.p.evaluate(()=>localStorage.getItem('mercury-skin-lab:presets:v1')),presets);}finally{await other.ctx.close()}});
 await check('runtime local request failures and transaction requests absent; external fonts recorded',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requestFailures.filter(r=>new URL(r.url).hostname==='127.0.0.1'),[]);assert.deepEqual(consoleErrors.filter(m=>!m.includes('net::ERR_NETWORK_ACCESS_DENIED')),[]);assert.deepEqual(mutations,[]);const remote=requestFailures.filter(r=>new URL(r.url).hostname!=='127.0.0.1');assert.ok(remote.every(r=>r.reason==='net::ERR_NETWORK_ACCESS_DENIED'));return {errors:0,localFailures:0,transactionRequests:0,externalFonts:[...new Set(remote.map(r=>r.url))]}});
}catch(e){checks.push({name:'flow',pass:false,error:e.stack})}
finally{if(ctx)await ctx.close();await browser.close();const result={pass:checks.filter(x=>x.pass).length,fail:checks.filter(x=>!x.pass).length,checks,errors,requestFailures,consoleErrors,mutations};await fs.writeFile(out+'ui-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({pass:result.pass,fail:result.fail,failures:checks.filter(x=>!x.pass)}));if(result.fail)process.exitCode=1;}
